# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Status

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          apt-get update && apt-get install -y python3-selenium
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run TDD tests
        run: nosetests
        env:
          DATABASE_URI: 'postgresql://postgres:postgres@postgres:5432/testdb'
      - name: Run BDD tests
        run: honcho start & (sleep 2 && behave)
        env:
          PORT: 5000
          DATABASE_URI: 'postgres://postgres:postgres@postgres:5432/testdb'
      - name: Upload coverage
        uses: codecov/codecov-action@v2
